import { Client, Equipment, Visit, Proposal, Ticket, AIOpportunity, NetworkTopology } from "@/types";

export const mockClients: Client[] = [
  {
    id: "1",
    business_name: "Clínica Salud Total",
    contact_person: "Dr. Carlos Méndez",
    email: "cmendez@saludtotal.pr",
    phone: "(787) 555-0101",
    secondary_phone: "(787) 555-0102",
    address: "Calle Principal #123",
    city: "Caguas",
    region: "Centro",
    business_type: "Clínica Médica",
    plan_type: "premium_ai",
    health_score: "good",
    monthly_value: 1200,
    total_revenue: 14400,
    active_since: "2023-01-15",
    last_visit_date: "2024-03-10",
    next_maintenance_date: "2024-04-15",
    notes: "Cliente premium con 15 estaciones de trabajo. Interesados en automatización de citas.",
    tags: ["healthcare", "premium", "ai-ready"],
    created_at: "2023-01-15T10:00:00Z",
    updated_at: "2024-03-10T14:30:00Z",
  },
  {
    id: "2",
    business_name: "Bufete Legal Rodríguez & Asociados",
    contact_person: "Lcda. María Rodríguez",
    email: "mrodriguez@bufeterlegal.pr",
    phone: "(787) 555-0201",
    address: "Ave. Muñoz Rivera #456",
    city: "San Juan",
    region: "Metro",
    business_type: "Bufete Legal",
    plan_type: "business",
    health_score: "excellent",
    monthly_value: 850,
    total_revenue: 10200,
    active_since: "2023-03-20",
    last_visit_date: "2024-03-05",
    next_maintenance_date: "2024-04-20",
    notes: "Red estable. Requieren backup diario y seguridad reforzada.",
    tags: ["legal", "security-focused"],
    created_at: "2023-03-20T09:00:00Z",
    updated_at: "2024-03-05T11:15:00Z",
  },
  {
    id: "3",
    business_name: "Gasolinera El Camino",
    contact_person: "Sr. José Torres",
    email: "jtorres@elcamino.pr",
    phone: "(787) 555-0301",
    address: "Carr. 172 Km 3.5",
    city: "Corozal",
    region: "Centro",
    business_type: "Gasolinera",
    plan_type: "basic",
    health_score: "fair",
    monthly_value: 450,
    total_revenue: 5400,
    active_since: "2023-06-10",
    last_visit_date: "2024-02-28",
    next_maintenance_date: "2024-04-10",
    notes: "Sistema POS antiguo. Oportunidad de upgrade y automatización de inventario.",
    tags: ["retail", "upgrade-needed"],
    created_at: "2023-06-10T08:30:00Z",
    updated_at: "2024-02-28T16:45:00Z",
  },
  {
    id: "4",
    business_name: "Colegio San Agustín",
    contact_person: "Prof. Ana Martínez",
    email: "amartinez@colegiosanagustin.pr",
    phone: "(787) 555-0401",
    address: "Calle Educación #789",
    city: "Cayey",
    region: "Centro",
    business_type: "Institución Educativa",
    plan_type: "premium_ai",
    health_score: "good",
    monthly_value: 1500,
    total_revenue: 18000,
    active_since: "2022-09-01",
    last_visit_date: "2024-03-12",
    next_maintenance_date: "2024-04-12",
    notes: "50+ computadoras. Red WiFi para estudiantes. Interesados en plataforma educativa con IA.",
    tags: ["education", "large-network", "ai-opportunity"],
    created_at: "2022-09-01T07:00:00Z",
    updated_at: "2024-03-12T13:20:00Z",
  },
  {
    id: "5",
    business_name: "Contadores Pérez CPA",
    contact_person: "CPA Juan Pérez",
    email: "jperez@perezCPA.pr",
    phone: "(787) 555-0501",
    address: "Edificio Profesional #202",
    city: "Aibonito",
    region: "Centro",
    business_type: "Firma Contable",
    plan_type: "business",
    health_score: "critical",
    monthly_value: 750,
    total_revenue: 9000,
    active_since: "2023-02-14",
    last_visit_date: "2024-03-08",
    next_maintenance_date: "2024-03-20",
    notes: "URGENTE: Servidor con fallas. Backup inconsistente. Requiere atención inmediata.",
    tags: ["accounting", "critical-status", "backup-issues"],
    created_at: "2023-02-14T10:30:00Z",
    updated_at: "2024-03-08T09:00:00Z",
  },
];

export const mockEquipment: Equipment[] = [
  {
    id: "eq1",
    client_id: "1",
    type: "desktop",
    brand: "Dell",
    model: "OptiPlex 7090",
    serial_number: "DELL-7090-001",
    location: "Recepción",
    status: "operational",
    os: "Windows 11 Pro",
    ram: "16GB",
    storage: "512GB SSD",
    ip_address: "192.168.1.10",
    health_score: "excellent",
    risk_level: "low",
    last_maintenance_date: "2024-03-10",
    next_maintenance_date: "2024-06-10",
    notes: "Equipo nuevo, funcionando perfectamente",
    created_at: "2023-01-15T10:00:00Z",
    updated_at: "2024-03-10T14:30:00Z",
  },
  {
    id: "eq2",
    client_id: "1",
    type: "server",
    brand: "HP",
    model: "ProLiant DL380",
    serial_number: "HP-DL380-001",
    location: "Sala de Servidores",
    status: "degraded",
    os: "Windows Server 2019",
    ram: "64GB",
    storage: "2TB RAID",
    ip_address: "192.168.1.5",
    health_score: "fair",
    risk_level: "medium",
    last_maintenance_date: "2024-02-15",
    next_maintenance_date: "2024-04-15",
    notes: "Temperatura elevada. Requiere limpieza de ventiladores.",
    created_at: "2023-01-15T10:00:00Z",
    updated_at: "2024-03-10T14:30:00Z",
  },
];

export const mockVisits: Visit[] = [
  {
    id: "v1",
    client_id: "1",
    technician_id: "tech1",
    visit_date: "2024-03-10",
    purpose: "Mantenimiento preventivo mensual",
    status: "completed",
    findings: "Sistema operando correctamente. Servidor con temperatura elevada.",
    recommendations: "Programar limpieza profunda del servidor. Considerar upgrade de sistema de enfriamiento.",
    photos: [],
    duration_hours: 3,
    follow_up_required: true,
    created_at: "2024-03-10T08:00:00Z",
    updated_at: "2024-03-10T14:30:00Z",
  },
  {
    id: "v2",
    client_id: "5",
    technician_id: "tech1",
    visit_date: "2024-03-08",
    purpose: "Emergencia - Servidor caído",
    status: "completed",
    findings: "Disco duro del servidor con sectores dañados. Backup desactualizado.",
    recommendations: "URGENTE: Reemplazo de disco duro. Implementar backup automático diario.",
    photos: [],
    duration_hours: 5,
    follow_up_required: true,
    created_at: "2024-03-08T09:00:00Z",
    updated_at: "2024-03-08T16:00:00Z",
  },
];

export const mockProposals: Proposal[] = [
  {
    id: "p1",
    client_id: "1",
    title: "Upgrade de Sistema de Enfriamiento + Automatización IA",
    description: "Propuesta para mejorar infraestructura de servidores e implementar sistema de citas con IA",
    services: [
      {
        id: "s1",
        name: "Sistema de Enfriamiento Profesional",
        description: "Instalación de rack cooling system",
        quantity: 1,
        unit_price: 1200,
        total: 1200,
      },
      {
        id: "s2",
        name: "Chatbot IA para Citas Médicas",
        description: "Desarrollo e implementación de asistente virtual",
        quantity: 1,
        unit_price: 3500,
        total: 3500,
      },
    ],
    total_amount: 4700,
    status: "sent",
    valid_until: "2024-04-15",
    terms: "50% al inicio, 50% al completar. Garantía de 1 año.",
    created_by: "admin1",
    created_at: "2024-03-11T10:00:00Z",
    updated_at: "2024-03-11T10:00:00Z",
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "t1",
    client_id: "5",
    title: "Servidor no responde",
    description: "El servidor principal no está accesible desde las estaciones de trabajo",
    priority: "critical",
    status: "completed",
    assigned_to: "tech1",
    category: "hardware",
    created_by: "client5",
    resolved_at: "2024-03-08T16:00:00Z",
    sla_due_date: "2024-03-08T12:00:00Z",
    created_at: "2024-03-08T09:00:00Z",
    updated_at: "2024-03-08T16:00:00Z",
  },
  {
    id: "t2",
    client_id: "3",
    title: "Sistema POS lento",
    description: "El punto de venta tarda mucho en procesar transacciones",
    priority: "high",
    status: "in_progress",
    assigned_to: "tech2",
    category: "software",
    created_by: "client3",
    sla_due_date: "2024-03-16T17:00:00Z",
    created_at: "2024-03-14T10:30:00Z",
    updated_at: "2024-03-14T11:00:00Z",
  },
];

export const mockAIOpportunities: AIOpportunity[] = [
  {
    id: "ai1",
    client_id: "1",
    title: "Automatización de Citas Médicas",
    description: "Implementar chatbot con IA para agendar citas, recordatorios automáticos y confirmaciones",
    category: "chatbot",
    impact_score: 9,
    time_savings_hours: 20,
    estimated_value: 3500,
    status: "proposed",
    created_at: "2024-03-10T14:30:00Z",
    updated_at: "2024-03-11T10:00:00Z",
  },
  {
    id: "ai2",
    client_id: "3",
    title: "Sistema de Inventario Inteligente",
    description: "IA para predecir demanda de combustible y optimizar órdenes de compra",
    category: "inventory",
    impact_score: 7,
    time_savings_hours: 10,
    estimated_value: 2800,
    status: "identified",
    created_at: "2024-02-28T16:45:00Z",
    updated_at: "2024-02-28T16:45:00Z",
  },
  {
    id: "ai3",
    client_id: "4",
    title: "Plataforma Educativa con IA",
    description: "Sistema de tutoría virtual y análisis de rendimiento estudiantil",
    category: "analytics",
    impact_score: 10,
    time_savings_hours: 40,
    estimated_value: 8500,
    status: "identified",
    created_at: "2024-03-12T13:20:00Z",
    updated_at: "2024-03-12T13:20:00Z",
  },
];

